name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]  # Run on all branches for pull requests
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install aqua
        uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.43.1

      - name: Build
        run: make build

      - name: Check formatting
        run: |
          make fmt | tee goimports.out
          if [ -s goimports.out ]; then
            echo "::error::Formatting issues found. Run 'make fmt' locally to fix them."
            exit 1
          fi

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
